### ISSUE TITLE
archive the dead project for public safety

### ISSUE THREAD

**Issue by ghost** [CipherShed/CipherShedBuilds#8]
from the code, the wiki and the issues, this should have been archived. is a dead project.

yes, https://www.ciphershed.org/download/ makes it seem like projects is active. as there is no notice that last release was **whenever it was**, there are **zero project releases**.

if someone wants to use it, archived repo means read-only access. so `git clone` works.
----
**peace out**
_ghostArch_

**Comment by pdinc-oss** [comment]
It is always available, not sure what you mean by archive the project for public safety.

As to the activity, we are committed to further development, would you like to contribute?
